site_name: Dissertation Docs Example
site_url: https://ryan-a-bell.github.io/dissertation-docs-example/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.integrate

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/js/extra.js


plugins:
  - search
  - mkdocs-jupyter
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - footnotes
nav:
- Home: index.md
- Generated:
  - Data:
    - Sample.Md: generated/data/sample.md
  - Index.Md: generated/index.md
  - New_Notebook.Ipynb: generated/new_notebook.ipynb
  - Notebooks:
    - Sample_Notebook.Ipynb: generated/notebooks/sample_notebook.ipynb
  - Pdfs:
    - Sample.Md: generated/pdfs/sample.md
  - Text:
    - Readme.Md: generated/text/readme.md
- Getting Started:
  - Index.Md: getting-started/index.md
- Guide.Md: guide.md
- Src:
  - New_Notebook.Ipynb: src/new_notebook.ipynb
  - Notebooks:
    - Sample_Notebook.Ipynb: src/notebooks/sample_notebook.ipynb
  - Text:
    - Readme.Md: src/text/readme.md
