site_name: Dissertation Docs Example
site_url: https://ryan-a-bell.github.io/dissertation-docs-example/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.integrate

extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/js/extra.js


plugins:
  - search
  - mkdocs-jupyter
  - mkdocs-gen-files
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - footnotes

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/index.md
  - API:
      - Package: api/index.md