site_name: Dissertation Docs Example
site_url: https://ryan-a-bell.github.io/dissertation-docs-example/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.integrate
    - navigation.sections
    - navigation.expand
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/nps_custom_css.css
extra_javascript:
  - assets/js/extra.js
  # Theme switcher disabled - uncomment line below to re-enable
  # - javascripts/mkdocs_theme_switcher.js


plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - table-reader
  - mkdocs-jupyter

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - footnotes
