name: Deploy MkDocs
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Generate docs
        run: |
          python scripts/generate_docs.py
      - name: Deploy
        run: |
          mkdocs gh-deploy --force
